# Generated by Django 3.0.8 on 2020-07-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='islaidu_tipai',
            name='aktyvus',
            field=models.BooleanField(default=False),
        ),
    ]
