# Generated by Django 3.0.8 on 2020-07-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontrole', '0002_islaidu_tipai_aktyvus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='islaidu_tipai',
            options={'ordering': ['aktyvus']},
        ),
    ]
