# Generated by Django 3.0.8 on 2020-07-26 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontrole', '0003_auto_20200726_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='islaidu_tipai',
            options={'ordering': ['-aktyvus']},
        ),
        migrations.CreateModel(
            name='Islaidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(blank=True, null=True, verbose_name='Data')),
                ('tiekejas', models.CharField(max_length=100, verbose_name='Tiekejas')),
                ('dokumento_nr', models.CharField(max_length=10, verbose_name='Dokumento numeris')),
                ('suma', models.FloatField(max_length=10, verbose_name='Suma')),
                ('tipas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kontrole.Islaidu_tipai')),
            ],
        ),
    ]
