# Generated by Django 3.0.8 on 2020-07-26 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrole', '0005_auto_20200726_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islaidos',
            name='data',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
