# Generated by Django 3.0.8 on 2020-07-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontrole', '0006_auto_20200726_1836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Islaidos',
        ),
    ]
