# Generated by Django 3.0.8 on 2020-07-26 16:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kontrole', '0007_delete_islaidos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='islaidu_tipai',
            options={'ordering': ['-aktyvus'], 'verbose_name': 'Išlaidų tipas', 'verbose_name_plural': 'Išlaidų tipai'},
        ),
        migrations.CreateModel(
            name='Islaidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('tiekejas', models.CharField(max_length=50, verbose_name='Tiekėjas')),
                ('dokumento_nr', models.CharField(max_length=15, verbose_name='Dokumento numeris')),
                ('suma', models.FloatField(max_length=100, verbose_name='Suma')),
                ('tipas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kontrole.Islaidu_tipai')),
            ],
            options={
                'verbose_name': 'Išlaida',
                'verbose_name_plural': 'Išlaidos',
                'ordering': ['data'],
            },
        ),
    ]
