# Generated by Django 3.0.8 on 2020-07-27 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontrole', '0009_auto_20200726_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='islaidos',
            options={'ordering': ['-data'], 'verbose_name': 'Išlaidos', 'verbose_name_plural': 'Išlaidos'},
        ),
    ]
